[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "2s"
  flush_jitter = "0s"
  precision = ""
  quiet = false

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = [
    "aquaponics/devices/+/telemetry"
  ]
  data_format = "json"
  name_override = "telemetry"
  tag_keys = [
    "deviceId"
  ]
  json_string_fields = [
    "timestamp"
  ]

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = [
    "aquaponics/devices/+/status"
  ]
  data_format = "json"
  name_override = "status"
  tag_keys = [
    "deviceId"
  ]
  json_string_fields = [
    "status",
    "reason"
  ]

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "aquaponics"
  skip_database_creation = false
